const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const rootDir = path.resolve(__dirname, "..");
const releaseDir = path.join(rootDir, "release");
const packageJson = require(path.join(rootDir, "package.json"));

const remoteRepo = process.env.OS_HERO_PAGES_REPO || "https://github.com/os-hero/os-hero.github.io.git";
const pagesDir = path.resolve(process.env.OS_HERO_PAGES_DIR || path.join(rootDir, "..", "os-hero.github.io"));
const updatesDir = path.join(pagesDir, "updates");

function run(command, args, options = {}) {
  execFileSync(command, args, {
    cwd: options.cwd || rootDir,
    stdio: "inherit"
  });
}

function runOutput(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: options.cwd || rootDir,
    encoding: "utf8"
  }).trim();
}

function ensureReleaseDir() {
  if (!fs.existsSync(releaseDir)) {
    throw new Error("release/ does not exist. Run npm run dist:mac or npm run dist first.");
  }
}

function ensurePagesRepo() {
  if (!fs.existsSync(pagesDir)) {
    run("git", ["clone", remoteRepo, pagesDir]);
    return;
  }

  if (!fs.existsSync(path.join(pagesDir, ".git"))) {
    throw new Error(`${pagesDir} exists but is not a git repository.`);
  }

  run("git", ["pull", "--ff-only"], { cwd: pagesDir });
}

function listUpdateArtifacts() {
  const files = fs.readdirSync(releaseDir);
  const currentVersion = packageJson.version;
  const artifactNames = files.filter((fileName) => {
    return (
      /^latest.*\.ya?ml$/.test(fileName) ||
      (/^OS Hero-.*\.(zip|dmg|blockmap)$/.test(fileName) && fileName.includes(currentVersion)) ||
      (/^OS Hero Setup .*\.(exe|blockmap)$/.test(fileName) && fileName.includes(currentVersion))
    );
  });

  if (!artifactNames.some((fileName) => fileName === "latest-mac.yml" || fileName === "latest.yml")) {
    throw new Error("No latest update metadata found in release/. Run npm run dist:mac or npm run dist:win first.");
  }

  if (!artifactNames.some((fileName) => fileName.includes(currentVersion))) {
    throw new Error(`No OS Hero ${currentVersion} update artifacts found in release/. Run npm run dist first.`);
  }

  return artifactNames;
}

function cleanLatestMetadata() {
  fs.mkdirSync(updatesDir, { recursive: true });

  for (const fileName of fs.readdirSync(updatesDir)) {
    if (/^latest.*\.ya?ml$/.test(fileName)) {
      fs.rmSync(path.join(updatesDir, fileName), { force: true });
    }
  }
}

function copyUpdateArtifacts(artifactNames) {
  for (const fileName of artifactNames) {
    fs.copyFileSync(path.join(releaseDir, fileName), path.join(updatesDir, fileName));
  }

  fs.writeFileSync(
    path.join(updatesDir, "README.md"),
    [
      "# OS Hero Updates",
      "",
      "This directory is the public electron-updater generic feed for OS Hero.",
      `Current release version: ${packageJson.version}`,
      "",
      "Do not hand-edit latest*.yml files. They are generated by electron-builder.",
      ""
    ].join("\n"),
    "utf8"
  );
}

function commitAndPush() {
  run("git", ["add", "updates"], { cwd: pagesDir });

  const status = runOutput("git", ["status", "--short", "updates"], { cwd: pagesDir });
  if (!status) {
    console.log("No update feed changes to deploy.");
    return;
  }

  run("git", ["commit", "-m", `Deploy OS Hero ${packageJson.version} updates`], { cwd: pagesDir });
  run("git", ["push"], { cwd: pagesDir });
}

function main() {
  ensureReleaseDir();
  const artifactNames = listUpdateArtifacts();
  ensurePagesRepo();
  cleanLatestMetadata();
  copyUpdateArtifacts(artifactNames);
  commitAndPush();

  console.log(`Deployed OS Hero ${packageJson.version} update feed to https://os-hero.github.io/updates/`);
}

main();
